<?php
header('Access-Control-Allow-Origin: *');
header('Content-Type: application/json');

$api_key = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzN2Q0YmQzMDM1ZmUxMWU5YTgwM2FiN2VlYjNjY2M5NyIsImp0aSI6IjQ5MGEzN2E4NmIxNTI1ODcxMTY0MjFhNDUzOTFkNGNiOTQ0YjJiNjk3YmQyMzY2MWVmNzY5NmViNzczNGQxZDYxNTJkZWMyYmE3OTliNzM1IiwiaWF0IjoxNzI4NTE0MzcxLjQ2MjcxMSwibmJmIjoxNzI4NTE0MzcxLjQ2MjcxMywiZXhwIjoxNzYwMDUwMzcxLjQ1NDEzLCJzdWIiOiIxMTQxODU4NyIsInNjb3BlcyI6WyJzaG9wcy5tYW5hZ2UiLCJzaG9wcy5yZWFkIiwiY2F0YWxvZy5yZWFkIiwib3JkZXJzLnJlYWQiLCJvcmRlcnMud3JpdGUiLCJwcm9kdWN0cy5yZWFkIiwicHJvZHVjdHMud3JpdGUiLCJ3ZWJob29rcy5yZWFkIiwid2ViaG9va3Mud3JpdGUiLCJ1cGxvYWRzLnJlYWQiLCJ1cGxvYWRzLndyaXRlIiwicHJpbnRfcHJvdmlkZXJzLnJlYWQiLCJ1c2VyLmluZm8iXX0.ADgCYU62aRaYr4FiYnRpfOXRO9NRmL8K5XaV3p6MhLdX1Gyue3XzwvLKvx_2CweY7oxbj42J582-1Ox8QrQ';

echo json_encode(['api_key' => $api_key]);
?>